name: Init CI
description: Sets up common environment for CI jobs

inputs:
  buildx:
    required: false
    description: Enable buildx system (needed just to enable some docker build-push-action features)
  gcp_service_account:
    required: false
    description: Login to gcloud and gcr with this service account (needed in order to push images and run gcloud)

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      if: ${{ inputs.buildx }}
    - name: Authenticate to Google Cloud
      if: ${{ inputs.gcp_service_account }}
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.gcp_service_account }}
    - name: Set up GCloud SDK
      if: ${{ inputs.gcp_service_account }}
      uses: google-github-actions/setup-gcloud@v0
    - name: Configure docker
      if: ${{ inputs.gcp_service_account }}
      shell: bash
      run: gcloud auth configure-docker
    - name: Generate build variables
      uses: actions/github-script@v6
      with:
        script: |
          core.exportVariable('IMAGE_NAME', `gcr.io/${context.repo.owner}/${context.repo.repo}`);
          const imageTag = `${process.env.GITHUB_REF_NAME}-${context.sha.substring(0, 8)}`;
          core.exportVariable('IMAGE_TAG', imageTag);
          core.exportVariable('IMAGE_TAG_BUILDER', `${imageTag}-builder`);
          core.exportVariable('IMAGE_TAG_STABLE', `${imageTag}-stable`);
